#
# CtrlRadBundle
#
ctrl_rad:
    resource: "@CtrlRadBundle/Resources/config/routing.yml"
ctrl_rad_controllers:
    resource: "@CtrlRadBundle/Controller/"
    type:     annotation

#
# custom routes
#
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
