security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha1

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: admin_
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }